# Generated by Django 4.1.7 on 2023-03-31 14:43

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('YOGA', 'Yoga'), ('SWIM', 'Swimming'), ('JOGG', 'Jogging'), ('CYCL', 'Cycling'), ('SPIN', 'Running'), ('LWGT', 'Lift Weight'), ('CCSK', 'Cross Country Skiing'), ('HIIT', 'High-intensity interval training')], max_length=4)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calories', models.FloatField()),
                ('label', models.CharField(choices=[('MEAL', 'Meal'), ('INGR', 'Ingredient')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('sleep', models.TimeField()),
                ('weight', models.FloatField()),
                ('waterCup', models.FloatField()),
                ('activities', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.activity')),
                ('meals', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.food')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthdate', models.DateField(validators=[django.core.validators.MinValueValidator(datetime.date(1923, 4, 25))])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(20.0)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(20.0)])),
                ('lifestyle', models.CharField(choices=[('ANO', 'No activity'), ('ALOW', 'Low activity'), ('AMED', 'Medium activity'), ('AINT', 'Intense activity'), ('APRO', 'Professional activity')], max_length=4)),
                ('goalType', models.CharField(choices=[('M', 'Maintain Weight'), ('L', 'Lose Weight'), ('G', 'Gain Weight')], max_length=1)),
                ('goalWeight', models.FloatField(validators=[django.core.validators.MinValueValidator(20.0)])),
                ('goalCalories', models.FloatField()),
                ('results', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.result')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
