# Generated by Django 4.1.7 on 2023-03-16 10:26

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('YOGA', 'Yoga'), ('SWIM', 'Swimming'), ('JOGG', 'Jogging'), ('CYCL', 'Cycling'), ('SPIN', 'Running'), ('LWGT', 'Lift Weight'), ('CCSK', 'Cross Country Skiing'), ('HIIT', 'High-intensity interval training')], max_length=4)),
                ('duration', models.DurationField(default=3600)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('calories', models.FloatField()),
                ('label', models.CharField(choices=[('MEAL', 'Meal'), ('INGR', 'Ingredient')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep', models.FloatField(default=7)),
                ('weight', models.FloatField()),
                ('waterIngested', models.FloatField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.activity')),
                ('meals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(20.0)])),
                ('goalWeight', models.FloatField(default=None, validators=[django.core.validators.MinValueValidator(20.0)])),
                ('goalType', models.CharField(choices=[('M', 'Maintain Weight'), ('L', 'Lose Weight'), ('G', 'Gain Weight')], default='L', max_length=1)),
                ('birthdate', models.DateField(default=None, validators=[django.core.validators.MinValueValidator(datetime.date(1923, 4, 10))])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('results', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.result')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
