# Generated by Django 4.2 on 2023-04-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='mealType',
            new_name='meal',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='meal',
            new_name='mealType',
        ),
    ]
